/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppKeysRouteImport } from './routes/_app/keys'
import { Route as AppModelsRouteImport } from './routes/_app/models'
import { Route as AppProvidersRouteRouteImport } from './routes/_app/providers/route'
import { Route as AppUsageRouteImport } from './routes/_app/usage'
import { Route as AppProvidersIndexRouteImport } from './routes/_app/providers/index'
import { Route as AppProvidersIdRouteImport } from './routes/_app/providers/$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppKeysRoute = AppKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppRoute,
} as any)
const AppModelsRoute = AppModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersRouteRoute = AppProvidersRouteRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AppRoute,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersIndexRoute = AppProvidersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProvidersRouteRoute,
} as any)
const AppProvidersIdRoute = AppProvidersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProvidersRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/providers': typeof AppProvidersRouteRouteWithChildren
  '/$': typeof AppSplatRoute
  '/keys': typeof AppKeysRoute
  '/models': typeof AppModelsRoute
  '/usage': typeof AppUsageRoute
  '/providers/$id': typeof AppProvidersIdRoute
  '/providers/': typeof AppProvidersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/keys': typeof AppKeysRoute
  '/models': typeof AppModelsRoute
  '/usage': typeof AppUsageRoute
  '/': typeof AppIndexRoute
  '/providers/$id': typeof AppProvidersIdRoute
  '/providers': typeof AppProvidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/providers': typeof AppProvidersRouteRouteWithChildren
  '/_app/$': typeof AppSplatRoute
  '/_app/keys': typeof AppKeysRoute
  '/_app/models': typeof AppModelsRoute
  '/_app/usage': typeof AppUsageRoute
  '/_app/': typeof AppIndexRoute
  '/_app/providers/$id': typeof AppProvidersIdRoute
  '/_app/providers/': typeof AppProvidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/providers'
    | '/$'
    | '/keys'
    | '/models'
    | '/usage'
    | '/providers/$id'
    | '/providers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$'
    | '/keys'
    | '/models'
    | '/usage'
    | '/'
    | '/providers/$id'
    | '/providers'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/providers'
    | '/_app/$'
    | '/_app/keys'
    | '/_app/models'
    | '/_app/usage'
    | '/_app/'
    | '/_app/providers/$id'
    | '/_app/providers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keys': {
      id: '/_app/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AppKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/models': {
      id: '/_app/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AppModelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/providers': {
      id: '/_app/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AppProvidersRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usage': {
      id: '/_app/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/providers/': {
      id: '/_app/providers/'
      path: '/'
      fullPath: '/providers/'
      preLoaderRoute: typeof AppProvidersIndexRouteImport
      parentRoute: typeof AppProvidersRouteRoute
    }
    '/_app/providers/$id': {
      id: '/_app/providers/$id'
      path: '/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof AppProvidersIdRouteImport
      parentRoute: typeof AppProvidersRouteRoute
    }
  }
}

interface AppProvidersRouteRouteChildren {
  AppProvidersIdRoute: typeof AppProvidersIdRoute
  AppProvidersIndexRoute: typeof AppProvidersIndexRoute
}

const AppProvidersRouteRouteChildren: AppProvidersRouteRouteChildren = {
  AppProvidersIdRoute: AppProvidersIdRoute,
  AppProvidersIndexRoute: AppProvidersIndexRoute,
}

const AppProvidersRouteRouteWithChildren =
  AppProvidersRouteRoute._addFileChildren(AppProvidersRouteRouteChildren)

interface AppRouteChildren {
  AppProvidersRouteRoute: typeof AppProvidersRouteRouteWithChildren
  AppSplatRoute: typeof AppSplatRoute
  AppKeysRoute: typeof AppKeysRoute
  AppModelsRoute: typeof AppModelsRoute
  AppUsageRoute: typeof AppUsageRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProvidersRouteRoute: AppProvidersRouteRouteWithChildren,
  AppSplatRoute: AppSplatRoute,
  AppKeysRoute: AppKeysRoute,
  AppModelsRoute: AppModelsRoute,
  AppUsageRoute: AppUsageRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
